function getQuestion() {
  var randomNumber = Math.floor((Math.random() * questionList.length));
  document.querySelector('main').innerHTML = questionList[randomNumber];
}

let questionList = [
  "What is your favorite color?",
  "What is your favorite food?",
  "What is your dream job?",
  "Where did you grow up?",
  "What would you do differently if you knew no one would judge you?",
  "If you could visit anywhere where would you go?",
  "What is your favorite book/author?",
  "If you could be anyone in history who would it be and why?",
  "If you could be any fictional character who would it be?",
  "If the world was going to end and you knew it, what 3 things would you do?",
  "What are your top 3 visted websites?",
  "When you replace a toilet paper roll, does the toilet paper go over or under?",
  "What is the best gift you ever got?",
  "What is the worst gift you ever got?",
  "What is your favorite song?",
  "What is something's the concerns you right now?",
  "When have you been the most proud of yourself?",
  "When have you been the most proud of someone else?",
  "What is something you wish you were better at?",
  "What is something you learned today?",
  "What is your favorite thing you did today?",
  "What is your favorite lyric from a song?",
  "What song impacted you the most or helped you through a difficult time?",
  "If you ever get married, where do you want to go on your honeymoon?",
  "Is there anyone you haven't forgiven?",
  "If price didn't matter, what is your dream car or vehicle?",
  "Who was your favorite teacher in high school and what did they teach?",
  "Have you met anyone famous?",
  "What is something you can't help but spend money on?",
  "If you could change something about the world, what would it be and why?",
  "What is the craziest thing you've done?",
  "If your job made you move, but you could choose which country you would be living in, which country would you choose and why?",
  "What is your favorite TV show?",
  "What is your worst habit?",
  "How would you describe yourself if you could only use five words?",
  "Do you have any phobias?",
  "What is your favorite day of the week?",
  "What are your pet peeves?",
  "What website would you say you never go a single day without viewing it?",
  "Would you rather regret doing something, or not doing it?",
  "What do you think your best characteristic is?",
  "If you were given the day off from all of your everyday responsibilities, how would you spend it?"
];
